[gdrive]
type = drive
scope = drive
client_id = 521951403423-r2h14eu7ei1cvchl342o9vltn9nda786.apps.googleusercontent.com
client_secret = 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
token = {"access_token":"ya29.a0AT3oNZ8gNyyZYiSNiwSIZ3K52nzURuQ31Z32VZFHlSLIUHHXQ_Pnu3H2LOIe4YgB5RqsIz3Dy4AG-yKfFIDIEcrUfSCAsFLr7t03XylAt_27eyzZR-CHBt7ncY0xp1FAdhhjv6Q5Cse63pylWOtkUI0lkR_0_VVCQgRf4l_MDlOVkIHpzFI1cgERl1-4nEWhjOCol8MaCgYKAUgSARMSFQHGX2Mi0-MNsrVLy21BXonkSI6qMA0206","token_type":"Bearer","refresh_token":"1//03NnpzTxsCHLRCgYIARAAGAMSNwF-L9IrV5EZUHnGbpArD9b6vJbmO_rvZWX5cRi2OuXvjx3HRzCwbKK8nFciUp9VI1L_sRYT9po","expiry":"2026-06-24T05:05:45.2029763+02:00","expires_in":3599}
team_drive = 
